sudo: required
services:
  - docker

before_install:
  - docker build -t chammycyx/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run chammycyx/complex npm test -- --coverage

after_success:
  - docker build -t chammycyx/docker-client ./client
  - docker build -t chammycyx/docker-nginx ./nginx
  - docker build -t chammycyx/docker-server ./server
  - docker build -t chammycyx/docker-worker ./worker

  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD

  - docker push chammycyx/docker-client
  - docker push chammycyx/docker-nginx
  - docker push chammycyx/docker-server
  - docker push chammycyx/docker-worker
